//
//  ViewedPresenter.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ViewedPresenter {

    // MARK: - Private properties -

    private unowned let view: ViewedViewInterface
    private let interactor: ViewedInteractorInterface
    private let wireframe: ViewedWireframeInterface

    var news = [News]()
    
    // MARK: - Lifecycle -

    init(view: ViewedViewInterface, interactor: ViewedInteractorInterface, wireframe: ViewedWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ViewedPresenter: ViewedPresenterInterface {
    
    func viewDidLoad() {
        
    }
    
    func numberOfItems(in section: Int) -> Int {
        return news.count
    }
    
    func didSelectRowAtIndexPath(_ indexPath: IndexPath) {
        wireframe.navigate(to: .details(news[indexPath.row]))
    }
}
