//
//  ViewedInterfaces.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ViewedWireframeInterface: WireframeInterface {
}

protocol ViewedViewInterface: NewsViewInterfase {
}

protocol ViewedPresenterInterface: NewsPresenterInterface {
}

protocol ViewedInteractorInterface: NewsInteractorInterface {
}
