//
//  DetailViewController.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailViewController: BaseViewController {

    // MARK: - Public properties -

    var presenter: DetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupTableView()
        presenter.viewDidLoad()
    }
    
    private func setupTableView() {
        tableView?.basicSettingsWith(self)
        tableView?.register(UINib(nibName: NewsDetailCell.cellID, bundle: nil), forCellReuseIdentifier: NewsDetailCell.cellID)
    }

}

//MARK: - UITableViewDataSource
extension DetailViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfItems(in: section)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        guard let cell = tableView.dequeueReusableCell(withIdentifier: NewsDetailCell.cellID, for: indexPath) as? NewsDetailCell else {
            return UITableViewCell()
        }
        
        return cell
    }
    
}

//MARK: - UITableViewDelegate
extension DetailViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}

// MARK: - DetailViewInterface

extension DetailViewController: DetailViewInterface {
    func setNavigationTitle(text: String) {
        self.navigationItem.title = text
    }
}
