//
//  DetailWireframe.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailWireframe: BaseWireframe {

    // MARK: - Module setup -

    init(news: News) {
        let moduleViewController = DetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = DetailInteractor()
        let presenter = DetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, news: news)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailWireframe: DetailWireframeInterface {
}
