//
//  EmailedInterfaces.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol EmailedWireframeInterface: WireframeInterface {
}

protocol EmailedViewInterface: ViewInterface {
}

protocol EmailedPresenterInterface: NewsPresenterInterface {
}

protocol EmailedInteractorInterface: InteractorInterface {
}
