//
//  EmailedPresenter.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EmailedPresenter {

    // MARK: - Private properties -

    private unowned let view: EmailedViewInterface
    private let interactor: EmailedInteractorInterface
    private let wireframe: EmailedWireframeInterface
    
    var news = [News]() {
        didSet {
            view.reloadData()
        }
    }

    // MARK: - Lifecycle -

    init(view: EmailedViewInterface, interactor: EmailedInteractorInterface, wireframe: EmailedWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - EmailedPresenterInterface
extension EmailedPresenter: EmailedPresenterInterface {
    func item(at indexPath: IndexPath) -> NewsViewItemInterface {
        return news[indexPath.row]
    }
    
    func viewDidLoad() {
        view.setLoadingVisible(true)
        
        interactor.getNewsBy(category: .emailed, period: 30) { [weak self] (news, error) in
            
            self?.view.setLoadingVisible(false)
            
            if let news = news {
                self?.news = news
            }
            else if let err = error {
                self?.view.showAlertWith(title: AlertString.kError, message: err.localizedDescription)
            }
        }
    }
    
    func numberOfItems(in section: Int) -> Int {
        return news.count
    }
    
    func didSelectRowAtIndexPath(_ indexPath: IndexPath) {
        wireframe.navigate(to: .details(news[indexPath.row]))
    }
}
