//
//  EmailedPresenter.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EmailedPresenter {

    // MARK: - Private properties -

    private unowned let view: EmailedViewInterface
    private let interactor: EmailedInteractorInterface
    private let wireframe: EmailedWireframeInterface
    
    var news = [News]()

    // MARK: - Lifecycle -

    init(view: EmailedViewInterface, interactor: EmailedInteractorInterface, wireframe: EmailedWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - EmailedPresenterInterface
extension EmailedPresenter: EmailedPresenterInterface {
    
    func viewDidLoad() {
        
    }
    
    func numberOfItems(in section: Int) -> Int {
        return news.count
    }
    
    func didSelectRowAtIndexPath(_ indexPath: IndexPath) {
        wireframe.navigate(to: .details(news[indexPath.row]))
    }
}
