//
//  EmailedInteractor.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EmailedInteractor {
    var network = Network(baseUrl: API.kUrlBaseString)
}

// MARK: - Extensions -

extension EmailedInteractor: EmailedInteractorInterface {
    func getNewsBy(category: NewsCategory, period: Int, completion: @escaping NewsResponseBlock) {
        network.getNewsBy(category: category, period: period) { (news, error) in
            completion(news, error)
        }
    }
}
