//
//  FavoritesPresenter.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FavoritesPresenter {

    // MARK: - Private properties -

    private unowned let view: FavoritesViewInterface
    private let interactor: FavoritesInteractorInterface
    private let wireframe: FavoritesWireframeInterface
    
    var news = [News]()

    // MARK: - Lifecycle -

    init(view: FavoritesViewInterface, interactor: FavoritesInteractorInterface, wireframe: FavoritesWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension FavoritesPresenter: FavoritesPresenterInterface {
    func favoritesButtonDidClick(_ index: Int) {}
    
    func trailingSwipeActionsForRowAt(indexPath: IndexPath) {
        self.interactor.deleteNews(news: [news[indexPath.row]]) { [weak self] success in
            if success {
                self?.news.remove(at: indexPath.row)
                self?.view.deleteRowAtIndexPath(indexPath)
            }
        }
    }
    
    func viewWillAppear() {
        getNews()
    }
    
    func item(at indexPath: IndexPath) -> NewsViewItemInterface {
        return news[indexPath.row]
    }
    
    func viewDidLoad() {
        view.setNavigationTitle(VCTitle.kFavorites)
        getNews()
    }
    
    func numberOfItems(in section: Int) -> Int {
        return news.count
    }
    
    func didSelectRowAtIndexPath(_ indexPath: IndexPath) {
        wireframe.navigate(to: .details(news[indexPath.row]))
    }
    
    //MARK -
    private func getNews() {
        interactor.getNews { [weak self] news in
            if let news = news {
                self?.news = news
            }
            else { self?.news = [News]() }
            
            self?.view.reloadData()
        }
    }
}
