//
//  FavoritesInteractor.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FavoritesInteractor {
    var databaseManager: DatabaseProtocol = CoreData.shared
}

// MARK: - Extensions -

extension FavoritesInteractor: FavoritesInteractorInterface {
    func getNews(completion: @escaping ([News]?) -> Void) {
        databaseManager.getNews { news in
            completion(news)
        }
    }
    
    func deleteNews(news: [News], completion: @escaping (Bool) -> Void) {
        databaseManager.deleteNews(news: news) { success in
            completion(success)
        }
    }
}
