//
//  FavoritesInterfaces.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FavoritesWireframeInterface: WireframeInterface {
}

protocol FavoritesViewInterface: NewsViewInterface {
    func deleteRowAtIndexPath(_ indexPath: IndexPath)
}

protocol FavoritesPresenterInterface: NewsPresenterInterface {
    func viewWillAppear()
    func trailingSwipeActionsForRowAt(indexPath: IndexPath)
}

protocol FavoritesInteractorInterface: InteractorInterface {
    var databaseManager: DatabaseManager { get }
    func getNews(completion:@escaping (_ news: [News]?) -> Void)
    func deleteNews(news: [News], completion:@escaping (_ success: Bool) -> Void)
}
