//
//  FavoritesInterfaces.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FavoritesWireframeInterface: WireframeInterface {
}

protocol FavoritesViewInterface: ViewInterface {
    func deleteRowAtIndexPath(_ indexPath: IndexPath)
    func reloadData()
    func setNavigationTitle(_ title: String)
    func showAlertWith(title: String?, message: String)
}

protocol FavoritesPresenterInterface: PresenterInterface {
    func trailingSwipeActionsForRowAt(indexPath: IndexPath)
    func item(at indexPath: IndexPath) -> NewsViewItemInterface
    var  news: [News] { get }
}

protocol FavoritesInteractorInterface: InteractorInterface {
    var  databaseManager: DatabaseProtocol { get }
    func getNews(completion:@escaping (_ news: [News]?) -> Void)
    func deleteNews(news: [News], completion:@escaping (_ success: Bool) -> Void)
}
