//
//  MainInterfaces.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MainWireframeInterface: WireframeInterface {
}

protocol MainViewInterface: ViewInterface {
}

protocol MainPresenterInterface: PresenterInterface {
}

protocol MainInteractorInterface: InteractorInterface {
}
