//
//  MainViewController.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainViewController: BaseTabBarController {

    // MARK: - properties
    private let tabBarTitles = [VCTitle.kEmailed,
                                VCTitle.kShared,
                                VCTitle.kViewed,
                                VCTitle.kFavorites]
    
    var presenter: MainPresenterInterface!

    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewControllers = setVCs()
        setupTabBarItems()
    }
    
    private func setVCs() -> [UIViewController] {
        let emailed = BaseNavigationController()
        emailed.setRootWireframe(NewsWireframe(type: .emailed))
        
        let shared = BaseNavigationController()
        shared.setRootWireframe(NewsWireframe(type: .shared))
        
        let viewed = BaseNavigationController()
        viewed.setRootWireframe(NewsWireframe(type: .viewed))
        
        let favorites = BaseNavigationController()
        favorites.setRootWireframe(FavoritesWireframe())
        
        return [emailed, shared, viewed, favorites]
    }
    
    private func setupTabBarItems() {
        viewControllers?.enumerated().forEach({ (i, view) in
            view.tabBarItem = UITabBarItem(title: tabBarTitles[i],
                                           image: UIImage(named: tabBarTitles[i].lowercased()),
                                           tag: i)
        })
    }

}

//MARK: - UITabBarControllerDelegate
extension MainViewController: UITabBarControllerDelegate {
    override func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        //interactor didSelect item
    }
}

//MARK: - MainViewInterface
extension MainViewController: MainViewInterface {
    
}
