//
//  MainInteractor.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainInteractor {
}

// MARK: - Extensions -

extension MainInteractor: MainInteractorInterface {
}
