//
//  SharedInterfaces.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SharedWireframeInterface: WireframeInterface {
}

protocol SharedViewInterface: NewsViewInterfase {
}

protocol SharedPresenterInterface: NewsPresenterInterface {
}

protocol SharedInteractorInterface: NewsInteractorInterface {
}
