//
//  SharedViewController.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SharedViewController: BaseViewController {

    // MARK: - Public properties -

    var presenter: SharedPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupNavigation()
    }
    
    //MARK: - private
    private func setupNavigation() {
        self.navigationItem.title = "Shared"
    }

}

// MARK: - Extensions -

extension SharedViewController: SharedViewInterface {
}
