//
//  NewsInteractor.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NewsInteractor {
    var network = Network(baseUrl: API.kUrlBaseString)
    var databaseManager: DatabaseManager = CoreDataManager.shared
}

// MARK: - Extensions -

extension NewsInteractor: NewsInteractorInterface {
    func getNewsBy(category: NewsCategory, period: Int, completion: @escaping NewsResponseBlock) {
        network.getNewsBy(category: category, period: period) { (news, error) in
            completion(news, error)
        }
    }
    
    func addNewsToFavorites(news: News, completion:@escaping (_ success: Bool, _ error: Error?) -> Void) {
        databaseManager.addNews(news: news) { success, error in
            completion(success, error)
        }
    }
    
    func deleteNews(news: [News], completion: @escaping (Bool) -> Void) {
        databaseManager.deleteNews(news: news) { success in
            completion(success)
        }
    }
}
