//
//  NewsWireframe.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewsWireframe: BaseWireframe {

    // MARK: - Module setup -

    init(type: NewsCategory) {
        let moduleViewController = NewsViewController()
        super.init(viewController: moduleViewController)

        let interactor = NewsInteractor()
        let presenter = NewsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, type: type)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension NewsWireframe: NewsWireframeInterface {
    
}
