//
//  NewsPresenter.swift
//  NY_TIMES
//
//  Created by Saul Goodman on 30.07.2020.
//  Copyright (c) 2020 Shvets. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NewsPresenter {

    // MARK: - Private properties -

    private unowned let view: NewsViewInterface
    private let interactor: NewsInteractorInterface
    private let wireframe: NewsWireframeInterface
    
    var news = [News]() {
        didSet {
            view.reloadData()
        }
    }
    
    private var type: NewsCategory!

    // MARK: - Lifecycle -

    init(view: NewsViewInterface, interactor: NewsInteractorInterface, wireframe: NewsWireframeInterface, type: NewsCategory) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.type = type
    }
}

// MARK: - EmailedPresenterInterface
extension NewsPresenter: NewsPresenterInterface {
    func favoritesButtonDidClick(_ index: Int) {
        interactor.addNewsToFavorites(news: [ news[index] ])
    }
    
    func item(at indexPath: IndexPath) -> NewsViewItemInterface {
        return news[indexPath.row]
    }
    
    func viewDidLoad() {
        view.setLoadingVisible(true)
        view.setNavigationTitle(type.getCategoryString())
        
        interactor.getNewsBy(category: self.type, period: 30) { [weak self] (news, error) in
            
            self?.view.setLoadingVisible(false)
            
            if let news = news {
                self?.news = news.sorted(by: { $0.updated! > $1.updated! })
            }
            else if let err = error {
                self?.view.showAlertWith(title: AlertString.kError, message: err.localizedDescription)
            }
        }
    }
    
    func numberOfItems(in section: Int) -> Int {
        return news.count
    }
    
    func didSelectRowAtIndexPath(_ indexPath: IndexPath) {
        wireframe.navigate(to: .details(news[indexPath.row]))
    }
}
